import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/User";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

const _userInfo = JSON.parse(cookies().get("key")?.value ?? "{}");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider userInfo={_userInfo}>{children}</UserProvider>
      </body>
    </html>
  );
}
